FROM node:16-alpine
WORKDIR '/app'
COPY ./package.json ./

# RUN mkdir -p /app/node_modules
# RUN chown node:node /app/node_modules

RUN npm install

# RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .
RUN chown -R node /app/node_modules
USER node

CMD ["npm", "run", "start"]