name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  buildRunDeploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build and Test client image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t docker.io/babismyl/react-test -f ./client/Dockerfile.dev ./client
        docker run -e CI=true babismyl/react-test npm run test -- --coverage

    - name: Build All Images and Push them in Docker Hub
      run: |
        docker build -t docker.io/babismyl/multi-client ./client 
        docker build -t docker.io/babismyl/multi-nginx ./nginx
        docker build -t docker.io/babismyl/multi-server ./server
        docker build -t docker.io/babismyl/multi-worker ./worker

        docker push docker.io/babismyl/multi-client
        docker push docker.io/babismyl/multi-nginx
        docker push docker.io/babismyl/multi-server      
        docker push docker.io/babismyl/multi-worker
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to AWS EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: multi-docker
        environment_name: Multidocker-env
        version_label: ${{ github.sha }}
        region: us-east-1
        existing_bucket_name: elasticbeanstalk-us-east-1-711496645742
        deployment_package: deploy.zip