name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  buildRunDeploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build and Run the Docker image
      run: |
#        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t docker.io/babismyl/complex -f Dockerfile.dev .
        docker run -e CI=true babismyl/complex npm run test
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to AWS EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: complex
        environment_name: Complex-env
        version_label: ${{ github.sha }}
        region: us-east-1
        existing_bucket_name: elasticbeanstalk-us-east-1-711496645742
        deployment_package: deploy.zip